version: "3.8"  # Updated to a widely supported version

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQLL_HOST: localhost
      MYSQL_DATABASE: contacts
      MYSQL_USER: root
      MYSQL_PASSWORD: Config.MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # Ensure compatibility

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/Config.NEO4J_PASSWORD  # Fixed value for simplicity
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data

  elasticsearch:
    image: elasticsearch:7.17.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Assumes a Dockerfile exists
    command: python dashboard/app.py
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - mongo
      - neo4j
      - elasticsearch
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Ensure logs are visible in real-time

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.utils.helpers worker --loglevel=info
    depends_on:
      - redis
      - app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
  es_data:
  redis_data: